// server/controllers/reportController.js
import PDFDocument from 'pdfkit';
import Response from '../models/Response.js';
import Form from '../models/Form.js';
import path from 'path';

export const generateSubmissionPDF = async (req, res) => {
  try {
    const { responseId } = req.params;
    const { detailed } = req.query;

    // 1. Fetch Data - Populating questionId to get question text and types
    const response = await Response.findById(responseId)
        .populate('formId')
        .populate('answers.questionId'); 
        
    if (!response) {
      return res.status(404).json({ message: 'Submission not found' });
    }

    const form = response.formId;
    const scorePercent = Math.round((response.score / response.totalMarks) * 100) || 0;

    // 2. Initialize PDF Stream
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    // Set headers for download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=Report-${response.username}.pdf`);

    doc.pipe(res);

    // --- PDF DESIGN ---

    // 1. Header / Branding
    doc.rect(0, 0, 595, 120).fill('#4F46E5'); // Indigo Header Background
    doc.fillColor('#FFFFFF').fontSize(24).font('Helvetica-Bold')
       .text('ASSESSMENT REPORT', 50, 45);
    
    doc.fontSize(10).font('Helvetica')
       .text('Generated by Formify Engine', 50, 75);

    // 2. Candidate Info
    doc.fillColor('#000000');
    doc.moveDown(4);
    
    doc.font('Helvetica-Bold').fontSize(14).text('Candidate Details');
    doc.rect(50, 165, 500, 70).strokeColor('#E2E8F0').stroke(); 
    
    doc.fontSize(10).font('Helvetica').text(`Name: ${response.username}`, 70, 180);
    doc.text(`Email: ${response.userEmail}`, 70, 195);
    doc.text(`Date: ${new Date(response.submittedAt).toLocaleDateString()}`, 300, 180);
    doc.text(`Submission ID: ${response._id}`, 300, 195);

    // 3. Score Card
    doc.moveDown(4);
    doc.font('Helvetica-Bold').fontSize(14).text('Performance Summary', 50, 260);

    doc.circle(100, 330, 40).lineWidth(3).strokeColor(scorePercent >= 70 ? '#10B981' : '#F43F5E').stroke();
    doc.fontSize(18).fillColor(scorePercent >= 70 ? '#10B981' : '#F43F5E')
       .text(`${scorePercent}%`, 82, 322);
    
    doc.fontSize(10).fillColor('#64748B').text('Total Score', 75, 380);

    doc.fillColor('#000000').fontSize(12).text('Points Achieved:', 200, 310);
    doc.font('Helvetica-Bold').text(`${response.score} / ${response.totalMarks}`, 350, 310);

    doc.font('Helvetica').text('Status:', 200, 330);
    doc.font('Helvetica-Bold').fillColor(scorePercent >= 50 ? '#10B981' : '#EF4444')
       .text(scorePercent >= 50 ? 'PASSED' : 'NEEDS IMPROVEMENT', 350, 330);

    // 4. AI Feedback Section
    if (response.aiFeedback) {
        doc.moveDown(6);
        doc.fillColor('#000000').font('Helvetica-Bold').fontSize(14).text('AI Evaluation', 50, 420);
        doc.fontSize(10).font('Helvetica-Oblique').fillColor('#475569')
           .text(response.aiFeedback, 50, 440, { width: 500, align: 'justify' });
    }

    // 5. Integrity Check
    if (response.integrityFlags && response.integrityFlags.length > 0) {
        doc.moveDown(2);
        doc.fillColor('#EF4444').font('Helvetica-Bold').fontSize(12).text('Integrity Flags Detected:', 50);
        
        response.integrityFlags.forEach((flag) => {
            doc.font('Helvetica').fontSize(10).fillColor('#EF4444')
               .text(`• ${flag.type} at ${new Date(flag.timestamp).toLocaleTimeString()}`);
        });
    }

    doc.fontSize(8).fillColor('#94A3B8').text('This document is automatically generated. Valid without signature.', 50, 750, { align: 'center' });

    // --- DETAILED BREAKDOWN PAGE ---
    if (detailed === 'true') {
        doc.addPage();
        
        doc.rect(0, 0, 595, 80).fill('#4F46E5');
        doc.fillColor('#FFFFFF').fontSize(20).font('Helvetica-Bold').text('Detailed Answer Breakdown', 50, 30);
        
        doc.fillColor('#000000');
        doc.moveDown(3);

        response.answers.forEach((ans, index) => {
            const q = ans.questionId;
            if (!q || ['Heading', 'Paragraph', 'Banner'].includes(q.type)) return;

            const content = q.content || {};
            const qText = content.question || content.text || `Question ${index + 1}`;
            const userAnswer = ans.answer;
            
            // Render Question Header
            doc.font('Helvetica-Bold').fontSize(11).fillColor('#000000').text(`Q${index + 1}: ${qText}`, { continued: true });
            doc.font('Helvetica').fontSize(9).fillColor('#64748B').text(`  (${ans.points} points)`);
            doc.moveDown(0.5);

            // --- SMART FORMATTER FOR DIFFERENT QUESTION TYPES ---
            
            if (q.type === 'Checkbox') {
                const uArr = Array.isArray(userAnswer) ? userAnswer : [];
                const cArr = Array.isArray(content.correctAnswers) ? content.correctAnswers : [];
                
                doc.font('Helvetica-Bold').fontSize(10).fillColor('#475569').text('Your Answer: ', { continued: true });
                doc.font('Helvetica').fillColor('#000000').text(uArr.length > 0 ? uArr.join(', ') : 'Not provided');
                
                if (cArr.length > 0) {
                    doc.font('Helvetica-Bold').fontSize(10).fillColor('#475569').text('Correct Answer: ', { continued: true });
                    doc.font('Helvetica').fillColor('#10B981').text(cArr.join(', '));
                }
            } 
            else if (q.type === 'Categorize') {
                doc.font('Helvetica-Bold').fontSize(10).fillColor('#475569').text('Your Answer:');
                if (userAnswer && typeof userAnswer === 'object' && Object.keys(userAnswer).length > 0) {
                    Object.entries(userAnswer).forEach(([cat, items]) => {
                        doc.font('Helvetica-Bold').fontSize(9).fillColor('#000000').text(`  • ${cat}: `, { continued: true });
                        doc.font('Helvetica').text(Array.isArray(items) ? items.join(', ') : items);
                    });
                } else {
                     doc.font('Helvetica').fontSize(9).fillColor('#000000').text('  Not provided');
                }

                const correctMapping = {};
                if (content.items) {
                    content.items.forEach(item => {
                        if (!correctMapping[item.category]) correctMapping[item.category] = [];
                        correctMapping[item.category].push(item.text);
                    });
                }
                if (Object.keys(correctMapping).length > 0) {
                    doc.moveDown(0.3);
                    doc.font('Helvetica-Bold').fontSize(10).fillColor('#475569').text('Correct Answer:');
                    Object.entries(correctMapping).forEach(([cat, items]) => {
                        doc.font('Helvetica-Bold').fontSize(9).fillColor('#10B981').text(`  • ${cat}: `, { continued: true });
                        doc.font('Helvetica').text(items.join(', '));
                    });
                }
            }
            else if (q.type === 'Comprehension') {
                 doc.font('Helvetica-Bold').fontSize(10).fillColor('#475569').text('Your Answers:');
                 if (content.mcqs && content.mcqs.length > 0) {
                     content.mcqs.forEach((mcq, i) => {
                         const uAns = userAnswer ? (userAnswer[mcq._id?.toString()] || userAnswer[i?.toString()] || userAnswer[i]) : null;
                         const isCorrect = String(uAns || '').trim().toLowerCase() === String(mcq.correctAnswer || '').trim().toLowerCase();
                         
                         doc.font('Helvetica-Oblique').fontSize(9).fillColor('#000000').text(`  ${i+1}. ${mcq.question || mcq.questionText}`);
                         doc.font('Helvetica-Bold').fontSize(9).fillColor('#475569').text(`      Answer: `, { continued: true });
                         doc.font('Helvetica').fillColor(isCorrect ? '#10B981' : '#F43F5E').text(`${uAns || 'Not provided'}`);
                         
                         if (!isCorrect && mcq.correctAnswer) {
                             doc.font('Helvetica-Bold').fontSize(9).fillColor('#475569').text(`      Correct: `, { continued: true });
                             doc.font('Helvetica').fillColor('#10B981').text(`${mcq.correctAnswer}`);
                         }
                         doc.moveDown(0.2);
                     });
                 }
            }
            else if (q.type === 'Cloze') {
                 const correctClozeAnswers = content.options || [];
                 doc.font('Helvetica-Bold').fontSize(10).fillColor('#475569').text('Your Answers (Blanks):');
                 
                 const uAnsArr = Array.isArray(userAnswer) ? userAnswer : [];
                 correctClozeAnswers.forEach((cAns, i) => {
                     const uAns = uAnsArr[i];
                     const isCorrect = String(uAns || '').trim().toLowerCase() === String(cAns || '').trim().toLowerCase();
                     
                     doc.font('Helvetica-Bold').fontSize(9).fillColor('#475569').text(`  Blank ${i+1}: `, { continued: true });
                     doc.font('Helvetica').fillColor(isCorrect ? '#10B981' : '#F43F5E').text(`${uAns || 'Not provided'}`);
                     
                     if (!isCorrect && cAns) {
                         doc.font('Helvetica-Bold').fontSize(9).fillColor('#475569').text(`      Correct: `, { continued: true });
                         doc.font('Helvetica').fillColor('#10B981').text(`${cAns}`);
                     }
                 });
            }
            else {
                // Fallback for standard String/Single Choice answers
                let userAnsStr = 'Not provided';
                if (userAnswer !== null && userAnswer !== undefined) {
                    userAnsStr = typeof userAnswer === 'object' ? JSON.stringify(userAnswer) : String(userAnswer);
                }
                
                doc.font('Helvetica-Bold').fontSize(10).fillColor('#475569').text('Your Answer: ', { continued: true });
                doc.font('Helvetica').fillColor('#000000').text(userAnsStr);

                let correctAnsStr = null;
                if (content.correctAnswer) {
                    correctAnsStr = String(content.correctAnswer);
                } else if (content.correctAnswers && Array.isArray(content.correctAnswers)) {
                    correctAnsStr = content.correctAnswers.join(', ');
                }

                if (correctAnsStr) {
                    doc.font('Helvetica-Bold').fontSize(10).fillColor('#475569').text('Correct Answer: ', { continued: true });
                    doc.font('Helvetica').fillColor('#10B981').text(correctAnsStr);
                }
            }

            doc.moveDown(1.5);
        });
    }

    doc.end();

  } catch (error) {
    console.error('PDF Gen Error:', error);
    res.status(500).json({ message: 'Failed to generate report' });
  }
};