// server/controllers/reportController.js
import PDFDocument from 'pdfkit';
import Response from '../models/Response.js';
import Form from '../models/Form.js';
import path from 'path';

export const generateSubmissionPDF = async (req, res) => {
  try {
    const { responseId } = req.params;

    // 1. Fetch Data
    const response = await Response.findById(responseId).populate('formId');
    if (!response) {
      return res.status(404).json({ message: 'Submission not found' });
    }

    const form = response.formId;
    const scorePercent = Math.round((response.score / response.totalMarks) * 100) || 0;

    // 2. Initialize PDF Stream
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    // Set headers for download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=Report-${response.username}.pdf`);

    doc.pipe(res); // Pipe PDF directly to the response

    // --- PDF DESIGN ---

    // 1. Header / Branding
    doc.rect(0, 0, 595, 120).fill('#4F46E5'); // Indigo Header Background
    doc.fillColor('#FFFFFF').fontSize(24).font('Helvetica-Bold')
       .text('ASSESSMENT REPORT', 50, 45);
    
    doc.fontSize(10).font('Helvetica')
       .text('Generated by NeuralForm Engine', 50, 75);

    // 2. Candidate Info (White Box)
    doc.fillColor('#000000');
    doc.moveDown(4);
    
    doc.font('Helvetica-Bold').fontSize(14).text('Candidate Details');
    doc.rect(50, 165, 500, 70).strokeColor('#E2E8F0').stroke(); // Border
    
    doc.fontSize(10).font('Helvetica').text(`Name: ${response.username}`, 70, 180);
    doc.text(`Email: ${response.userEmail}`, 70, 195);
    doc.text(`Date: ${new Date(response.submittedAt).toLocaleDateString()}`, 300, 180);
    doc.text(`Submission ID: ${response._id}`, 300, 195);

    // 3. Score Card
    doc.moveDown(4);
    doc.font('Helvetica-Bold').fontSize(14).text('Performance Summary', 50, 260);

    // Draw Score Circle (Simulated)
    doc.circle(100, 330, 40).lineWidth(3).strokeColor(scorePercent >= 70 ? '#10B981' : '#F43F5E').stroke();
    doc.fontSize(18).fillColor(scorePercent >= 70 ? '#10B981' : '#F43F5E')
       .text(`${scorePercent}%`, 82, 322);
    
    doc.fontSize(10).fillColor('#64748B').text('Total Score', 75, 380);

    // Stat Grid
    doc.fillColor('#000000').fontSize(12).text('Points Achieved:', 200, 310);
    doc.font('Helvetica-Bold').text(`${response.score} / ${response.totalMarks}`, 350, 310);

    doc.font('Helvetica').text('Status:', 200, 330);
    doc.font('Helvetica-Bold').fillColor(scorePercent >= 50 ? '#10B981' : '#EF4444')
       .text(scorePercent >= 50 ? 'PASSED' : 'NEEDS IMPROVEMENT', 350, 330);

    // 4. AI Feedback Section (if exists)
    if (response.aiFeedback) {
        doc.moveDown(6);
        doc.fillColor('#000000').font('Helvetica-Bold').fontSize(14).text('AI Evaluation', 50, 420);
        doc.fontSize(10).font('Helvetica-Oblique').fillColor('#475569')
           .text(response.aiFeedback, 50, 440, { width: 500, align: 'justify' });
    }

    // 5. Integrity Check
    if (response.integrityFlags && response.integrityFlags.length > 0) {
        doc.moveDown(2);
        doc.fillColor('#EF4444').font('Helvetica-Bold').fontSize(12).text('Integrity Flags Detected:', 50);
        
        response.integrityFlags.forEach((flag, i) => {
            doc.font('Helvetica').fontSize(10).fillColor('#EF4444')
               .text(`• ${flag.type} at ${new Date(flag.timestamp).toLocaleTimeString()}`);
        });
    }

    // Footer
    doc.fontSize(8).fillColor('#94A3B8').text('This document is automatically generated. Valid without signature.', 50, 750, { align: 'center' });

    // Finalize
    doc.end();

  } catch (error) {
    console.error('PDF Gen Error:', error);
    res.status(500).json({ message: 'Failed to generate report' });
  }
};