// client/src/components/Analytics/ReportTemplate.jsx
import { Shield, Award, Activity, BarChart } from 'lucide-react';

export default function ReportTemplate({ data }) {
  if (!data) return null;

  return (
    <div id="neural-report" className="hidden print:block p-16 bg-white text-black min-h-screen">
      {/* Header */}
      <div className="flex justify-between items-start border-b-4 border-black pb-8 mb-12">
        <div>
          <h1 className="text-4xl font-black uppercase tracking-tighter mb-2">Neural Assessment Report</h1>
          <p className="font-mono text-xs text-gray-500 uppercase tracking-widest">System: Formify Core v4.0</p>
        </div>
        <div className="bg-black text-white p-4 rounded-xl text-right">
          <p className="text-[10px] uppercase font-bold opacity-50">Integrity Score</p>
          <p className="text-2xl font-black">{data.integrityScore || '98'}%</p>
        </div>
      </div>

      {/* Overview Grid */}
      <div className="grid grid-cols-3 gap-8 mb-16">
        <div className="p-6 border-2 border-black rounded-2xl">
          <p className="text-[10px] font-black uppercase mb-2">Participant</p>
          <p className="text-lg font-bold">{data.respondentName}</p>
        </div>
        <div className="p-6 border-2 border-black rounded-2xl">
          <p className="text-[10px] font-black uppercase mb-2">Module Title</p>
          <p className="text-lg font-bold">{data.formTitle}</p>
        </div>
        <div className="p-6 border-2 border-black rounded-2xl">
          <p className="text-[10px] font-black uppercase mb-2">Final Accuracy</p>
          <p className="text-lg font-bold text-indigo-600">{data.score}%</p>
        </div>
      </div>

      {/* Proctoring Logs */}
      <div className="mb-16">
        <h3 className="text-xs font-black uppercase tracking-[0.3em] mb-6 flex items-center gap-2">
          <Shield size={14} /> Proctoring Intelligence Log
        </h3>
        <div className="space-y-4">
          {data.violations?.length > 0 ? (
            data.violations.map((v, i) => (
              <div key={i} className="flex justify-between p-4 bg-gray-50 rounded-lg border-l-4 border-red-500">
                <span className="font-bold">{v.type}</span>
                <span className="font-mono text-gray-400">{v.timestamp}</span>
              </div>
            ))
          ) : (
            <div className="p-4 bg-green-50 rounded-lg border-l-4 border-green-500 font-bold text-green-700">
              No integrity violations detected during the session.
            </div>
          )}
        </div>
      </div>

      {/* AI Semantic Feedback */}
      <div className="p-8 bg-black text-white rounded-[32px]">
        <h3 className="text-xs font-black uppercase tracking-[0.3em] mb-4 flex items-center gap-2 text-indigo-400">
          <Award size={14} /> AI Semantic Evaluation
        </h3>
        <p className="text-lg leading-relaxed italic">
          "{data.aiFeedback || 'The participant demonstrated a high level of conceptual understanding with minor deviations in technical nomenclature.'}"
        </p>
      </div>

      {/* Footer */}
      <footer className="fixed bottom-16 left-16 right-16 border-t pt-8 flex justify-between text-[10px] font-mono text-gray-400 uppercase">
        <span>Generated by Formify Neural Engine</span>
        <span>{new Date().toLocaleString()}</span>
      </footer>
    </div>
  );
}